"use client"

import React, { useState, useEffect } from "react"
import { usePathname, useRouter } from "next/navigation"
import { Sun, Moon, Info, Plus, Calendar, Download, Globe } from "lucide-react"
import { Button } from "@heroui/react"
import { fetchWebsites } from "@/lib/api"

const pageTitleMap: Record<string, { title: string; info: string }> = {
  "/admin/dashboard": { title: "Dashboard", info: "Overview of active properties, publication queue & AI metrics" },
  "/admin/websites": { title: "Websites", info: "Manage target CMS properties, domain credentials & schedules" },
  "/admin/sources": { title: "Sources", info: "Data intake engine: RSS feeds, Google News & API streams" },
  "/admin/custom-agents": { title: "Agent", info: "Configure AI agents, skill assignments & integration permissions" },
  "/admin/workflows": { title: "Workflow", info: "Visual node graph engine for multi-agent publishing pipelines" },
  "/admin/analytics": { title: "Analytics", info: "30-day traffic velocity, top ranking keywords & publication performance" },
  "/admin/articles": { title: "Articles", info: "Article library, live posts, and draft management" },
  "/admin/keywords": { title: "Keyword", info: "Keyword research, cluster analysis & SEO search volume" },
  "/admin/media": { title: "Media", info: "Featured artwork library generated by fal.ai & Freepik" },
  "/admin/integrations": { title: "Integration", info: "API connections: WordPress, fal.ai, OpenAI, Google News" },
  "/admin/newsletters": { title: "Newsletter", info: "Email newsletter automation & subscriber campaigns" },
  "/admin/settings": { title: "Settings", info: "Platform settings, organization profiles & system preferences" }
}

const DEMO_WEBSITES = [
  { id: "all", name: "All Websites" },
  { id: "site-1", name: "AI News" },
  { id: "site-2", name: "Tech Blog" },
  { id: "site-3", name: "Finance Blog" },
  { id: "site-4", name: "Travel Blog" }
]

export function Header() {
  const pathname = usePathname() || "/admin/dashboard"
  const router = useRouter()
  const [theme, setTheme] = useState<"light" | "dark">("light")
  const [showTooltip, setShowTooltip] = useState(false)
  const [websites, setWebsites] = useState<any[]>(DEMO_WEBSITES)
  const [selectedSiteId, setSelectedSiteId] = useState<string>("all")
  const [dateRange, setDateRange] = useState<string>("30d")

  useEffect(() => {
    async function loadWebsites() {
      const data = await fetchWebsites()
      if (data && data.length > 0) {
        setWebsites([
          { id: "all", name: "All Websites" },
          ...data.map((w: any) => ({ id: w.id, name: w.name }))
        ])
      }
    }
    loadWebsites()
  }, [])

  const toggleTheme = () => {
    const nextTheme = theme === "light" ? "dark" : "light"
    setTheme(nextTheme)
    if (nextTheme === "dark") {
      document.documentElement.classList.add("dark")
      document.documentElement.classList.remove("light")
    } else {
      document.documentElement.classList.add("light")
      document.documentElement.classList.remove("dark")
    }
  }

  // Always dispatch event — pages listen and open their own modal
  const handleOpenModal = () => {
    window.dispatchEvent(new CustomEvent("open-admin-modal"))
  }

  const handleSiteChange = (val: string) => {
    setSelectedSiteId(val)
    window.dispatchEvent(new CustomEvent("analytics-site-change", { detail: { siteId: val } }))
  }

  const handleDateChange = (val: string) => {
    setDateRange(val)
    window.dispatchEvent(new CustomEvent("analytics-date-change", { detail: { dateRange: val } }))
  }

  // Find page title info
  const currentPageKey = Object.keys(pageTitleMap).find((key) =>
    pathname === key || pathname.startsWith(`${key}/`)
  )
  const currentInfo = currentPageKey ? pageTitleMap[currentPageKey] : { title: "AI OS", info: "Autonomous AI Publishing Platform" }

  return (
    <header className="h-14 border-b border-divider bg-content1 px-6 flex items-center justify-between sticky top-0 z-20">
      {/* Left: Page title */}
      <div className="flex items-center gap-2 relative">
        <span className="text-sm font-semibold">{currentInfo.title}</span>
        <div
          className="relative flex items-center"
          onMouseEnter={() => setShowTooltip(true)}
          onMouseLeave={() => setShowTooltip(false)}
        >
          <Info className="size-3.5 text-default-400 hover:text-foreground cursor-pointer transition-colors" />
          {showTooltip && (
            <div className="absolute left-6 top-0 w-64 p-2.5 bg-content1 text-foreground text-xs rounded-large border border-divider shadow-medium z-50 pointer-events-none leading-relaxed">
              {currentInfo.info}
            </div>
          )}
        </div>
      </div>

      {/* Right: Dynamic action controls */}
      <div className="flex items-center gap-2">
        {pathname.startsWith("/admin/analytics") && (
          <>
            <select
              value={selectedSiteId}
              onChange={(e) => handleSiteChange(e.target.value)}
              className="h-8 px-3 text-xs bg-background text-foreground border border-divider rounded-medium focus:outline-none"
              aria-label="Select website"
            >
              {websites.map((w) => (
                <option key={w.id} value={w.id}>{w.name}</option>
              ))}
            </select>

            <select
              value={dateRange}
              onChange={(e) => handleDateChange(e.target.value)}
              className="h-8 px-3 text-xs bg-background text-foreground border border-divider rounded-medium focus:outline-none"
              aria-label="Select date range"
            >
              <option value="7d">Last 7 Days</option>
              <option value="30d">Last 30 Days</option>
              <option value="90d">Last 90 Days</option>
              <option value="ytd">Year to Date</option>
            </select>

            <Button variant="outline" size="sm"><Download className="size-3.5"  /> 
              Export
            </Button>
          </>
        )}

        {pathname.startsWith("/admin/websites") && (
          <Button size="sm" onPress={handleOpenModal}><Plus className="size-3.5"  /> 
            Add Website
          </Button>
        )}

        {pathname.startsWith("/admin/custom-agents") && (
          <Button size="sm" onPress={handleOpenModal}><Plus className="size-3.5"  /> 
            Create Agent
          </Button>
        )}

        {pathname.startsWith("/admin/websites") && (
          <Button size="sm" variant="primary" onPress={() => router.push("/admin/websites/new")}>
            <Plus className="size-3.5" /> Add Website
          </Button>
        )}

        {pathname.startsWith("/admin/custom-agents") && (
          <Button size="sm" variant="primary" onPress={() => router.push("/admin/custom-agents/new")}>
            <Plus className="size-3.5" /> Create Agent
          </Button>
        )}

        {pathname.startsWith("/admin/workflows") && (
          <Button size="sm" variant="primary" onPress={() => router.push("/admin/workflows")}>
            <Plus className="size-3.5" /> Create Workflow
          </Button>
        )}

        {pathname.startsWith("/admin/sources") && (
          <Button size="sm" variant="primary" onPress={() => router.push("/admin/sources/new")}>
            <Plus className="size-3.5" /> Add Source
          </Button>
        )}

        {pathname.startsWith("/admin/integrations") && (
          <Button size="sm" variant="primary" onPress={() => router.push("/admin/integrations")}>
            <Plus className="size-3.5" /> Add Integration
          </Button>
        )}

        {pathname.startsWith("/admin/articles") && (
          <Button size="sm" variant="primary" onPress={() => router.push("/admin/articles/new")}>
            <Plus className="size-3.5" /> Create Article
          </Button>
        )}

        {pathname.startsWith("/admin/keywords") && (
          <Button size="sm" variant="primary" onPress={() => router.push("/admin/keywords")}>
            <Plus className="size-3.5" /> Research Keyword
          </Button>
        )}

        {pathname.startsWith("/admin/media") && (
          <Button size="sm" variant="primary" onPress={() => router.push("/admin/media")}>
            <Plus className="size-3.5" /> Upload Media
          </Button>
        )}

        <button
          onClick={toggleTheme}
          className="size-8 rounded-medium border border-divider flex items-center justify-center text-default-400 hover:text-foreground hover:bg-default-100 transition-colors ml-1"
          title={`Switch to ${theme === "light" ? "Dark" : "Light"} Mode`}
        >
          {theme === "light" ? <Moon className="size-4" /> : <Sun className="size-4" />}
        </button>
      </div>
    </header>
  )
}
